RDK-460: Add wide channel support to wifi_pushRadioChannel2
rdkcentral/hal-wifi-cfg80211 pull request #23
Opened 2022-03-10 08:40 UTC by tomasz-kilarski-plume

Signed-off-by: Tomasz Kilarski <tkilarski@plume.com>

2022-03-10 08:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/hal-wifi-cfg80211?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/hal-wifi-cfg80211?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/hal-wifi-cfg80211?pullRequest=23) it.</sub>

2022-03-10 11:46 UTC, mhughesacn commented on source/wifi/wifi_hal.c
> +/*
Hi Tomasz: Please change from "This component includes" to "This file includes...".  If all the Plume code is all in one place, these two lines should go in front of that code instead at the start of the file.
Thanks,
Martin Hughes, RDK CMF Compliance Team

2022-03-11 13:13 UTC, manigandanj requested changes

2022-03-11 13:13 UTC, manigandanj commented on source/wifi/wifi_hal.c
> +	_syscmd(cmd, buf, sizeof(buf));
please correct indent.

2022-03-11 13:28 UTC, tomasz-kilarski-plume commented
indentation fixed

2022-03-11 14:20 UTC, manigandanj approved these changes

2022-03-11 14:20 UTC, merged