BD-1023: Compliance Problems in hal-wifi-cfg80211
rdkcentral/hal-wifi-cfg80211 pull request #3
Opened 2021-07-30 12:02 UTC by manigandanj

Signed-off-by: Manigandan Gopalakrishnan <manigandan.gopalakrishnan@ltts.com>

2021-07-30 12:48 UTC, mhughesacn requested changes
Hi Manigandan - please see my comments - thanks.

2021-07-30 12:48 UTC, mhughesacn commented on source/wifi/client_wifi_hal.c
>  #include <fcntl.h>
Still missing header please

2021-07-30 12:48 UTC, mhughesacn commented on source/wifi/client_wifi_hal.h
> +#ifndef __CLIENT_WIFI_HAL_H__
Missing header on new file

2021-07-30 12:48 UTC, mhughesacn commented on source/wifi/wifi_hal.c
> +//Code in rxStatsInfo_callback, txStatsInfo_callback and in chanSurveyInfo_callback originates from:
Please use the text in BD-1023 on this line:
"Code in rxStatsInfo_callback and other callbacks is credited as follows:"

2021-07-30 14:20 UTC, mhughesacn approved these changes

2021-07-30 14:36 UTC, mhughesacn commented
Hi Manigandan: Please will you make one more change which I noticed when I went back to the repo: Before the actual text of the ISC License at line 209, please will you put in a title as follows, and remove the Copyright for Johannes Berg?  (NOTICE is where the actual copyrights are given.)

ISC License
===========
Copyright YEAR AUTHOR

2021-08-04 11:36 UTC, mhughesacn commented on NOTICE
> +ISC License
Sorry, crossed line here: please delete lines 13-15 and put them instead into the file called LICENSE before the text of the ISC license.  The LICENSE file is in the same directory as NOTICE.

2021-08-04 12:20 UTC, mhughesacn commented on LICENSE
>  Copyright 2007 Johannes Berg
Sorry Manigandan - want this line deleted too (line 208, Johannes Berg)

2021-08-04 12:47 UTC, mhughesacn commented
Thanks Manigandan.  I cleared the blockages in the tool as well, and now it scans clean.

2021-08-04 12:59 UTC, rajkumar154 approved these changes

2021-08-04 13:00 UTC, merged